{"name": "test_ddt[4-4-7]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 7, got 8\nassert 8 == 7\n +  where 7 = int('7')", "trace": "self = <test_add.TestAdd object at 0x7fff16f083d0>, a = '4', b = '4', c = '7'\n\n    @pytest.mark.ddt\n    @pytest.mark.parametrize(\n        \"a,b,c\",\n        read_csv(\"data.csv\")\n    )\n    def test_ddt(self, a, b, c):\n        res = add(int(a), int(b))\n>       assert res == int(c), f\"Expected {c}, got {res}\"\nE       AssertionError: Expected 7, got 8\nE       assert 8 == 7\nE        +  where 7 = int('7')\n\nunit_tests/test_add.py:78: AssertionError"}, "attachments": [{"name": "log", "source": "e06a3f9b-5226-441a-8e0d-dc02f5575e7e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "'4'"}, {"name": "b", "value": "'4'"}, {"name": "c", "value": "'7'"}], "start": 1750463947045, "stop": 1750463947045, "uuid": "7cce5443-e8ed-49f1-be5b-3f7aad06a221", "historyId": "628e69e6ad9a003afe330d97ce432588", "testCaseId": "af20dd0ff6a3d82a80eb46698afa9280", "fullName": "unit_tests.test_add.TestAdd#test_ddt", "labels": [{"name": "tag", "value": "ddt"}, {"name": "parentSuite", "value": "unit_tests"}, {"name": "suite", "value": "test_add"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "mb5"}, {"name": "thread", "value": "59509-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit_tests.test_add"}]}