{"uid":"196c9e6d4355e231","name":"test_list1","fullName":"unit_tests.test_add.TestAdd#test_list1","historyId":"6f9ec05af584e70b86f4005288e423e7","time":{"start":1750369304768,"stop":1750369304768,"duration":0},"status":"skipped","statusMessage":"XFAIL\n\nAssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\n  \n  Right contains one more item: 5\n  \n  Full diff:\n    [\n        1,\n        2,...\n  \n  ...Full output truncated (4 lines hidden), use '-vv' to show","statusTrace":"self = <test_add.TestAdd object at 0x768311916f60>\n\n    @pytest.mark.xfail  # expected to be failed, and actual failed, xfailed\n    @pytest.mark.api\n    def test_list1(self):\n        res = add([1], [2, 3, 4])\n>       assert res == [1, 2, 3, 4, 5]\nE       AssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\nE         \nE         Right contains one more item: 5\nE         \nE         Full diff:\nE           [\nE               1,\nE               2,...\nE         \nE         ...Full output truncated (4 lines hidden), use '-vv' to show\n\nunit_tests/test_add.py:53: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"ff","time":{"start":1750369303693,"stop":1750369303693,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"f","time":{"start":1750369303693,"stop":1750369303693,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL\n\nAssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\n  \n  Right contains one more item: 5\n  \n  Full diff:\n    [\n        1,\n        2,...\n  \n  ...Full output truncated (4 lines hidden), use '-vv' to show","statusTrace":"self = <test_add.TestAdd object at 0x768311916f60>\n\n    @pytest.mark.xfail  # expected to be failed, and actual failed, xfailed\n    @pytest.mark.api\n    def test_list1(self):\n        res = add([1], [2, 3, 4])\n>       assert res == [1, 2, 3, 4, 5]\nE       AssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\nE         \nE         Right contains one more item: 5\nE         \nE         Full diff:\nE           [\nE               1,\nE               2,...\nE         \nE         ...Full output truncated (4 lines hidden), use '-vv' to show\n\nunit_tests/test_add.py:53: AssertionError","steps":[],"attachments":[{"uid":"82962829b7f9f9f0","name":"log","source":"82962829b7f9f9f0.txt","type":"text/plain","size":243}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"f::0","time":{"start":1750369304790,"stop":1750369304790,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"api"},{"name":"parentSuite","value":"unit_tests"},{"name":"suite","value":"test_add"},{"name":"subSuite","value":"TestAdd"},{"name":"host","value":"ubuntu"},{"name":"thread","value":"6086-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"unit_tests.test_add"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["api"]},"source":"196c9e6d4355e231.json","parameterValues":[]}