{"uid":"df83e9f49832e107","name":"test_list1","fullName":"unit_tests.test_add.TestAdd#test_list1","historyId":"6f9ec05af584e70b86f4005288e423e7","time":{"start":1750463947033,"stop":1750463947033,"duration":0},"status":"skipped","statusMessage":"XFAIL\n\nAssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\n  \n  Right contains one more item: 5\n  \n  Full diff:\n    [\n        1,\n        2,...\n  \n  ...Full output truncated (4 lines hidden), use '-vv' to show","statusTrace":"self = <test_add.TestAdd object at 0x7fff16efe710>\n\n    @pytest.mark.xfail  # expected to be failed, and actual failed, xfailed\n    @pytest.mark.api\n    def test_list1(self):\n        res = add([1], [2, 3, 4])\n>       assert res == [1, 2, 3, 4, 5]\nE       AssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\nE         \nE         Right contains one more item: 5\nE         \nE         Full diff:\nE           [\nE               1,\nE               2,...\nE         \nE         ...Full output truncated (4 lines hidden), use '-vv' to show\n\nunit_tests/test_add.py:53: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"f","time":{"start":1750463946108,"stop":1750463946108,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ff","time":{"start":1750463946108,"stop":1750463946108,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL\n\nAssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\n  \n  Right contains one more item: 5\n  \n  Full diff:\n    [\n        1,\n        2,...\n  \n  ...Full output truncated (4 lines hidden), use '-vv' to show","statusTrace":"self = <test_add.TestAdd object at 0x7fff16efe710>\n\n    @pytest.mark.xfail  # expected to be failed, and actual failed, xfailed\n    @pytest.mark.api\n    def test_list1(self):\n        res = add([1], [2, 3, 4])\n>       assert res == [1, 2, 3, 4, 5]\nE       AssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\nE         \nE         Right contains one more item: 5\nE         \nE         Full diff:\nE           [\nE               1,\nE               2,...\nE         \nE         ...Full output truncated (4 lines hidden), use '-vv' to show\n\nunit_tests/test_add.py:53: AssertionError","steps":[],"attachments":[{"uid":"9b45743cfbd5a744","name":"log","source":"9b45743cfbd5a744.txt","type":"text/plain","size":243}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"f::0","time":{"start":1750463947067,"stop":1750463947067,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"api"},{"name":"parentSuite","value":"unit_tests"},{"name":"suite","value":"test_add"},{"name":"subSuite","value":"TestAdd"},{"name":"host","value":"mb5"},{"name":"thread","value":"59509-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"unit_tests.test_add"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["api"]},"source":"df83e9f49832e107.json","parameterValues":[]}